### ISSUE TITLE
Move to analytics.js

### ISSUE THREAD

**Issue by rod** [danielbayerlein/middleman-google-analytics#27]
Google recommends [analytics.js](https://developers.google.com/analytics/devguides/collection/analyticsjs/#the_javascript_tracking_snippet) for tracking. Any thoughts on upgrading from ga.js?

**Comment by rod** [comment]
😓  just saw the #15, pretend this never happened.

**Comment by danielbayerlein** [comment]
With version 3.0, I will remove ga.js.
