### ISSUE TITLE
Multiple tracking ids

### ISSUE THREAD

**Issue by DRogueRonin** [danielbayerlein/middleman-google-analytics#29]
From what I understand, this is not intended.

In my case my customer and I both have an id because they want to track their page via their account and we track it for verification and convenience that everything is working.

Or is there some other intended way? If not, I could make a Pull Request unless you want to do the changes yourself.

**Comment by danielbayerlein** [comment]
@DRogue1337 That makes sense. This feature will come with the next release.

https://developers.google.com/analytics/devguides/collection/analyticsjs/creating-trackers#working_with_multiple_trackers
