### ISSUE TITLE
remove type="text/javascript"

### ISSUE THREAD

**Issue by ch4mpignator** [danielbayerlein/middleman-google-analytics#30]
when using ga.output = :html it generates  type="text/javascript" which is unnecessary.

**Comment by danielbayerlein** [comment]
@x-ch4mp-x You're welcome to submit a pull request :gal

**Comment by danielbayerlein** [comment]
PR #31

**Comment by danielbayerlein** [comment]
fe94dac553f4fe4ab19ce19738d82628f1f96284
