### ISSUE TITLE
Could not find gem 'middleman-google-analytics'

### ISSUE THREAD

**Issue by xiazhaoyang** [danielbayerlein/middleman-google-analytics#36]
Hi Daniel

When I trying to deploy my website on Netlify, it failed because it could not find 'middleman-google-analytics' in gem source. 

Sam

**Comment by danielbayerlein** [comment]
Sorry @xiazhaoyang, I've no experience with Netlify...

**Comment by xiazhaoyang** [comment]
I have figured out that it's because gem 'middleman-google-analytics' only works in Ruby v.2.3.1 in Netlify, but not v.2.4.3, I change the Ruby version to v2.3.1 in Netlify then it ran well.

**Comment by danielbayerlein** [comment]
@xiazhaoyang Feel free to update the `middleman-google-analytics` gem to Ruby 2.4.
